title: Kavin Arasu - Portfolio
author: Kavin Arasu
email: kavinarasu22@gmail.com
description: Kavin Arasu -  AI, Machine Learning, NLP, Python
url: "https://iamkavinarasu.github.io"
github_username:  iamkavinarasu

theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
